### ISSUE TITLE
refactor: `WEB_DIRECTORY` instead of copying to web path

### ISSUE THREAD

**Issue by ltdrdata** [DrJKL/ComfyUI-Anchors#2]
Copying web files to web directory isn't recommended.
That way has various weakness.

Try this way.

https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/c269c5c01a82dc5113c60fdfb482dee33727690a/__init__.py#L34

**Comment by chrisgoringe** [comment]
indeed ... https://github.com/chrisgoringe/cg-use-everywhere/issues/64
